name: To Eternal Happiness
favicon: null
layout_spectrum: 0.8835509766358882
typography_spectrum: 0.32569563016295433
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.31826858152635396
  lightness: 0.45845004520379007
  saturation: 0.6716704196296632
  rhythmicContrast: 0.1807427096646279
purpose: []
